name: Auto Pull

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: auto pull
    strategy:
      matrix:
        include:
          - server_id: 1
            user: twoblade
            dir: ~/GaryPics

          - server_id: 2
            user: gary
            dir: ~/GaryPics

          - server_id: 3
            user: zach
            dir: ~/documents/GaryPics

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ matrix.server_id == 1 && secrets.SERVER_IP_1 || secrets.SERVER_IP_2 }}
          username: ${{ matrix.user }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          debug: true
          script: |
            cd ${{ matrix.dir }}
            git pull --ff-only
